import Header from "@/layout/Header";
import Main from "@/layout/Main";
import Sidebar from "@/layout/Sidebar";
import localFont from "next/font/local";
import "./globals.css";
import LayoutProvider from "@/context/layout";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`font-sans antialiased h-screen grid grid-rows-[auto_1fr] grid-cols-[240px_1fr]`}
      >
        <LayoutProvider>
          <Header />
          <Sidebar />
        </LayoutProvider>
        <Main>
          {children}
        </Main>
      </body>
    </html>
  );
}
