import Header from "@/layouts/Header";
import Main from "@/layouts/Main";
import Sidebar from "@/layouts/Sidebar";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen grid grid-rows-[auto_1fr] grid-cols-[auto_1fr]`}
      >
        <Header />
        <Sidebar />
        <Main>
          {children}
        </Main>
      </body>
    </html>
  );
}
